### ISSUE TITLE
TP1 terminé

### ISSUE THREAD

**Issue by M-Garrigues** [PolytechLyon/2019-isi3-graph-grandjean_garrigues#1]
Bonjour Antoine, 

Nous avons terminé ce TP, si tu veux nous faire un premier retour!

Cordialement

**Comment by Slashgear** [comment]
- [ ] J'insiste mais je souhaite que le Rapport soit dans le Rapport.md et non dans un PDF à part (sinon je ne peux pas vous indiquer mes retours sur le rapport correctement.
- [ ] Afin de me confirmer que vous avez bien compris, Quels sont les raisons de l'usage du pattern Adapter? quelle situation vous indiquer que c'est ce pattern qui résoudra le mieux votre problème d'implémentation
- [ ] Pouvez vous m'indiquer la différence entre un Set et une List en Java ?
Ici devrait-on utiliser un Set plutôt qu'une List ?
https://github.com/PolytechLyon/2019-isi3-graph-grandjean_garrigues/blob/7dd877bde9fd5bd0580b973d96cc3f447d81c4bf/src/main/java/graph/Graph.java#L55
- [ ] Connaissez vous l'API stream de Java 8 ? (j'ai vu que vous l'avez utilisé ailleurs mais entrainez vous sur ce `toString` )
https://github.com/PolytechLyon/2019-isi3-graph-grandjean_garrigues/blob/7dd877bde9fd5bd0580b973d96cc3f447d81c4bf/src/main/java/graph/Graph.java#L101
- [ ] Bien vu pour les itérateurs, je pense qu'on pourrait ici utiliser deux types abstraits de Collection en Java qui permettront de définir une file et une pile

**Comment by M-Garrigues** [comment]
C'est tout bon?
